<!doctype html>
<html>
<head>
  <title><?php echo $formatter->escape($title); ?></title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
<?php if ($useStyleSheet) { ?>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<?php } ?>
</head>
<body>
<div id="main">
<?php if (APPLICATION_MODE != 'PRODUCTION') { ?>

  <h1>TESTING MODE,
    @see&nbsp;application/config.php, @see&nbsp;README</h1>

<?php } ?>
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $controllerPath; ?>"><?php echo $formatter->escape($title); ?></a>
      </div>

      <div class="collapse navbar-collapse">
        <?php
          require 'index-search-form.phtml';
        ?>
      </div>
    </div>
  </div>
