<form class="navbar-form navbar-right" role="search" action="<?php echo $controllerPath; ?>/lookup" method="get">
  <div class="form-group">
    <input type="text" name="search" id="search-key-input" class="form-control" placeholder="Search for a public key"
      value="<?php if (isset($search)) { echo $search; } ?>"
      >
  </div>
  <div class="form-group">
    <label class="radio-inline" for="radio-index">
      <input type="radio" id="radio-index" name="op" value="index" checked="checked" />
      simple
    </label>
    <label class="radio-inline" for="radio-vindex">
      <input type="radio" id="radio-vindex" name="op" value="vindex">
      verbose
    </label>
  </div>
  <div class="form-group">
    <?php if ($isAdminMode) { ?>
      <input type="hidden" name="fingerprint" value="on">
    <?php } else { ?>
      <label class="checkbox-inline" for="checkbox-fingerprint">
        <input type="checkbox" id="checkbox-fingerprint" name="fingerprint" value="on" checked="checked">
        show fingerprints
      </label>
    <?php } ?>
  </div>

  <button type="submit" class="btn btn-default">Search</button>
</form>
