<?php require 'header.phtml'; ?>
  <div class="container">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Type</th>
          <th>bits / keyID</th>
          <th>cr. time</th>
          <th>exp time</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($keys as $lines) {
          foreach ($lines as $line) {
        ?>
          <tr<?php if ($line['recordType'] == 'pub') { echo ' class="active"'; } ?>>
          <?php
            if ($line['recordType'] == 'pub') {
              printf(
                "<td>pub</td><td>%s / %s</td><td>%s</td><td>%s</td><td></td>\n",
                $line['bits'],
                $formatter->formatKeyIdLink($controllerPath, $line['keyId']),
                $formatter->formatTst($line['creationTst']),
                $formatter->formatTst($line['expirationTst'])
              );
            }

            elseif ($line['recordType'] == 'fpr' and $showFingerprint) {
              printf(
                "<td><small>fpr</small></td><td colspan=\"4\">%s</td>\n",
                $formatter->formatFingerprint($line['fingerprint'])
              );

              if ($isAdminMode) {
                require 'admin-remove-form.phtml';
              }
            }

            elseif ($line['recordType'] == 'uid') {
              printf(
                "<td><small>uid</small></td><td colspan=\"4\">%s</td>\n",
                htmlentities($line['userId'], ENT_HTML5));
            }

            elseif ($line['recordType'] == 'sig') {
              printf(
                "<td><small>sig</small></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td>\n",
                $formatter->formatKeyIdLink($controllerPath, $line['keyId']),
                $formatter->formatTst($line['creationTst']),
                $formatter->formatTst($line['expirationTst']),
                $formatter->formatGetLink(
                  $controllerPath, $line['keyId'], $line['userId']
                )
              );
            }
          }
        ?>
            </tr>
<?php } ?>
<?php require 'footer.phtml'; ?>
