<?php require 'header.phtml'; ?>
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Type</th>
        <th>bits / keyID</th>
        <th>Date</th>
        <th>User ID</th>
        <?php if ($isAdminMode) { echo '<th></th>'; } ?>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($keys as $lines) {
          foreach ($lines as $line) { ?>
              <tr<?php if ($line['recordType'] == 'pub') { echo ' class="active"'; } ?>>
          <?php
            $showAdminRemoveForm = false;
            if ($line['recordType'] == 'pub') {
              printf(
                "<td>pub</td><td>%s / %s</td><td>%s</td><td>%s</td>\n",
                $line['bits'],
                $formatter->formatKeyIdLink($controllerPath, $line['keyId']),
                $formatter->formatTst($line['creationTst']),
                $formatter->formatGetLink(
                  $controllerPath, $line['keyId'], $line['userId']
                )
              );
            }

            elseif ($line['recordType'] == 'fpr' and $showFingerprint) {
              printf(
                "<td><small>fpr</small></td><td colspan=\"3\">%s</td>\n",
                $formatter->formatFingerprint($line['fingerprint'])
              );

              if ($isAdminMode) {
                $showAdminRemoveForm = true;
              }
            }

            elseif ($line['recordType'] == 'uid') {
              printf(
                "                               %s\n",
                htmlentities($line['userId'], ENT_HTML5)
              );
            }
            if ($isAdminMode) {
              echo '<td>';
              if ($showAdminRemoveForm) {
                require 'admin-remove-form.phtml';
              }
              echo '</td>';
            }
            ?></tr>
            <?php
          }
        } ?>
    </tbody>
  </table>
</div>

<?php require 'footer.phtml'; ?>
