<?php require 'header.phtml'; ?>
<pre>Type bits/keyID     Date       User ID</pre>
<?php foreach ($keys as $lines) { ?>
<hr />
<pre><?php
  foreach ($lines as $line) {
    if ($line['recordType'] == 'pub') {
      printf(
        "pub  %s/%s  %s %s\n",
        $line['bits'],
        $formatter->formatKeyIdLink($controllerPath, $line['keyId']),
        $formatter->formatTst($line['creationTst']),
        $formatter->formatGetLink(
          $controllerPath, $line['keyId'], $line['userId']
        )
      );
    }

    elseif ($line['recordType'] == 'fpr' and $showFingerprint) {
      printf(
        "         Fingerprint=%s\n",
        $formatter->formatFingerprint($line['fingerprint'])
      );

      if ($isAdminMode) {
        require 'admin-remove-form.phtml';
      }
    }

    elseif ($line['recordType'] == 'uid') {
      printf(
        "                               %s\n",
        htmlentities($line['userId'], ENT_HTML5)
      );
    }
  }
?></pre>
<?php } ?>
<?php require 'footer.phtml'; ?>